package org.example.app

import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

/**
 * Configuration for generating a Gradle multi-module project
 */
data class GradleProjectConfig(
    val projectName: String,
    val outputDirectory: Path,
    val wireVersion: String = "5.3.5",
    val kotlinVersion: String = "2.2.20",
    val javaVersion: Int = 21
)

/**
 * Result of Gradle project generation
 */
data class GenerationResult(
    val outputDirectory: Path,
    val modulesGenerated: List<String>,
    val filesGenerated: List<String>,
    val success: Boolean,
    val message: String
)

/**
 * Generates Gradle multi-module projects with Wire configuration
 */
class GradleProjectGenerator(
    private val config: GradleProjectConfig
) {

    /**
     * Generate a complete Gradle project from module grouping result
     */
    fun generate(
        groupingResult: ModuleGroupingResult,
        protoSourcePath: Path
    ): GenerationResult {
        val generatedFiles = mutableListOf<String>()

        try {
            // Create output directory
            config.outputDirectory.createDirectories()

            // 1. Generate settings.gradle.kts
            val settingsFile = generateSettings(groupingResult)
            generatedFiles.add(settingsFile)

            // 2. Generate root build.gradle.kts
            val rootBuildFile = generateRootBuild()
            generatedFiles.add(rootBuildFile)

            // 3. Generate per-module build.gradle.kts files
            groupingResult.modules.forEach { module ->
                val moduleBuildFile = generateModuleBuild(module, protoSourcePath)
                generatedFiles.add(moduleBuildFile)
            }

            // 4. Generate .gitignore
            val gitignoreFile = generateGitignore()
            generatedFiles.add(gitignoreFile)

            return GenerationResult(
                outputDirectory = config.outputDirectory,
                modulesGenerated = groupingResult.modules.map { it.name },
                filesGenerated = generatedFiles,
                success = true,
                message = "Successfully generated Gradle project with ${groupingResult.modules.size} modules"
            )
        } catch (e: Exception) {
            return GenerationResult(
                outputDirectory = config.outputDirectory,
                modulesGenerated = emptyList(),
                filesGenerated = generatedFiles,
                success = false,
                message = "Failed to generate project: ${e.message}"
            )
        }
    }

    /**
     * Generate settings.gradle.kts
     */
    private fun generateSettings(groupingResult: ModuleGroupingResult): String {
        val content = buildString {
            appendLine("/*")
            appendLine(" * Generated by proto-build-generator")
            appendLine(" * https://github.com/square/wire")
            appendLine(" */")
            appendLine()
            appendLine("pluginManagement {")
            appendLine("    repositories {")
            appendLine("        gradlePluginPortal()")
            appendLine("        mavenCentral()")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("plugins {")
            appendLine("    id(\"org.gradle.toolchains.foojay-resolver-convention\") version \"1.0.0\"")
            appendLine("}")
            appendLine()
            appendLine("rootProject.name = \"${config.projectName}\"")
            appendLine()

            // Include all modules
            val moduleNames = groupingResult.modules
                .map { it.name }
                .sorted() // Deterministic ordering
                .joinToString(", ") { "\"$it\"" }

            appendLine("include($moduleNames)")
        }

        val file = config.outputDirectory.resolve("settings.gradle.kts")
        file.writeText(content)
        return "settings.gradle.kts"
    }

    /**
     * Generate root build.gradle.kts
     */
    private fun generateRootBuild(): String {
        val content = buildString {
            appendLine("/*")
            appendLine(" * Generated by proto-build-generator")
            appendLine(" * Root build configuration for all modules")
            appendLine(" */")
            appendLine()
            appendLine("plugins {")
            appendLine("    kotlin(\"jvm\") version \"${config.kotlinVersion}\" apply false")
            appendLine("    id(\"com.squareup.wire\") version \"${config.wireVersion}\" apply false")
            appendLine("}")
            appendLine()
            appendLine("allprojects {")
            appendLine("    repositories {")
            appendLine("        mavenCentral()")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("subprojects {")
            appendLine("    apply(plugin = \"org.jetbrains.kotlin.jvm\")")
            appendLine("    apply(plugin = \"com.squareup.wire\")")
            appendLine()
            appendLine("    extensions.configure<JavaPluginExtension> {")
            appendLine("        toolchain {")
            appendLine("            languageVersion.set(JavaLanguageVersion.of(${config.javaVersion}))")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    extensions.configure<com.squareup.wire.gradle.WireExtension> {")
            appendLine("        kotlin {}")
            appendLine("    }")
            appendLine("}")
        }

        val file = config.outputDirectory.resolve("build.gradle.kts")
        file.writeText(content)
        return "build.gradle.kts"
    }

    /**
     * Generate build.gradle.kts for a specific module
     */
    private fun generateModuleBuild(module: ProtoModule, protoSourcePath: Path): String {
        val content = buildString {
            appendLine("/*")
            appendLine(" * Generated by proto-build-generator")
            appendLine(" * Module: ${module.name}")
            appendLine(" * Package: ${module.packageName ?: "N/A"}")
            appendLine(" * Protos: ${module.protoCount}")
            appendLine(" */")
            appendLine()

            // Calculate relative path from module to proto source directory
            val moduleDir = config.outputDirectory.resolve(module.name)
            val relativeProtoPath = moduleDir.relativize(protoSourcePath).toString()

            // Wire configuration
            appendLine("wire {")

            // sourcePath with includes for files to generate
            appendLine("    sourcePath {")
            appendLine("        srcDir(\"$relativeProtoPath\") {")
            module.protoFiles.sortedBy { it.path }.forEach { protoNode ->
                appendLine("            include(\"${protoNode.path}\")")
            }
            appendLine("        }")
            appendLine("    }")
            appendLine()

            // protoPath for dependencies
            if (module.dependencies.isNotEmpty()) {
                appendLine("    protoPath {")
                module.dependencies.sorted().forEach { dep ->
                    appendLine("        srcDir(project(\":$dep\").layout.projectDirectory.dir(\"$relativeProtoPath\"))")
                }
                appendLine("    }")
                appendLine()
            }

            appendLine("    kotlin {")
            appendLine("    }")
            appendLine("}")
            appendLine()

            // Dependencies
            if (module.dependencies.isNotEmpty()) {
                appendLine("dependencies {")
                module.dependencies.sorted().forEach { dep ->
                    appendLine("    implementation(project(\":$dep\"))")
                }
                appendLine("}")
            }
        }

        val moduleDir = config.outputDirectory.resolve(module.name)
        moduleDir.createDirectories()

        val file = moduleDir.resolve("build.gradle.kts")
        file.writeText(content)
        return "${module.name}/build.gradle.kts"
    }

    /**
     * Generate .gitignore for the generated project
     */
    private fun generateGitignore(): String {
        val content = buildString {
            appendLine("# Gradle")
            appendLine(".gradle/")
            appendLine("build/")
            appendLine("!gradle/wrapper/gradle-wrapper.jar")
            appendLine()
            appendLine("# IDE")
            appendLine(".idea/")
            appendLine("*.iml")
            appendLine(".vscode/")
            appendLine()
            appendLine("# Generated code")
            appendLine("**/generated/")
            appendLine()
            appendLine("# OS")
            appendLine(".DS_Store")
            appendLine("Thumbs.db")
        }

        val file = config.outputDirectory.resolve(".gitignore")
        file.writeText(content)
        return ".gitignore"
    }
}
