/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("com.squareup.wire:wire-schema:5.3.5")
    implementation("com.squareup.okio:okio:3.9.0")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.DependencyGraphDemoKt"
}
